### PR TITLE
Update the solutions for some extra cases of the datum

### PR DESCRIPTION
**Pull request by D1051237**
Update the code by adding some case solving methods , listed following:
1. Add the solutions for the values(rel_0 and elevation) are not in the desired range by using append() and insert() for the last value and first value, so they are in the range because I create them as the new border.
Problems still ongoing, listed following:
1. As the new border set for the out range values we get 4778 correct out of 4898 but still a little datum are wrong for some reason, so I'm still on progressing.

@alecwu44743 please check my code, thank you very much. :P
My Name Is Shi ~

### CODE REVIEW

**Review by alecwu44743 — APPROVED** [review]

**Comment by alecwu44743** [comment]
It seems like we're nearly finished with this.
However, have you identified the issues with the remaining data? 🤔

**Comment by D1051237** [comment]
@alecwu44743 
Dear Alec , I had finished programing the code and solved all the problem occurred before, and the results are all completed and correct.
Please check my code and thank for your attention, my buddy  d (> U < ) b

**Comment by alecwu44743** [comment]
Could you explain simply how you solve the problems? 🤩

**Comment by D1051237** [comment]
@alecwu44743 
Of course my man, I encounter the problem that when I delete the duplicated value in list, I found that if I use index in list as the parameter of for loop, it can cause the wrong index, which in advance cause wrong rel_0 and elevation and get invalid, so I change the way to deal with this case by using the value in list ,e.g. list_value in x_ext[:], which it can solve the index shifting while removing the duplicated value.
Hope this can make you  understand. > /// <

**Comment by alecwu44743** [comment]
Okay, I understand. xD
It's great to see the project nearing completion. I appreciate your contributions during these days. Thank you! 😊

**Review by alecwu44743 — APPROVED** [review]

**Pull request merged**
